[package]
name = "crossbeam"
# When publishing a new version:
# - Update CHANGELOG.md
# - Update README.md
# - Create "crossbeam-X.Y.Z" git tag
version = "0.6.0"
authors = ["The Crossbeam Project Developers"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/crossbeam-rs/crossbeam"
homepage = "https://github.com/crossbeam-rs/crossbeam"
documentation = "https://docs.rs/crossbeam"
description = "Tools for concurrent programming"
keywords = ["atomic", "garbage", "non-blocking", "lock-free", "rcu"]
categories = ["concurrency", "memory-management", "data-structures"]
exclude = ["/ci/*", "/.travis.yml", "/bors.toml"]

[badges]
travis-ci = { repository = "crossbeam-rs/crossbeam" }

[features]
default = ["std"]
nightly = ["crossbeam-epoch/nightly", "crossbeam-utils/nightly"]
std = ["crossbeam-epoch/std", "crossbeam-utils/std"]

[dependencies]
cfg-if = "0.1"
lazy_static = "1.1.0"
parking_lot = "0.7"

[dependencies.crossbeam-channel]
version = "0.3.4"
path = "./crossbeam-channel"

[dependencies.crossbeam-deque]
version = "0.6.3"
path = "./crossbeam-deque"

[dependencies.crossbeam-epoch]
version = "0.7.0"
path = "./crossbeam-epoch"

[dependencies.crossbeam-utils]
version = "0.6.3"
path = "./crossbeam-utils"

[dev-dependencies]
rand = "0.6"

[workspace]
members = [
  ".",
  "crossbeam-channel",
  "crossbeam-channel/benchmarks",
  "crossbeam-deque",
  "crossbeam-epoch",
  "crossbeam-skiplist",
  "crossbeam-utils",
]

# [patch.crates-io]
# crossbeam = { path = "." }
# crossbeam-channel = { path = "./crossbeam-channel" }
# crossbeam-deque = { path = "./crossbeam-deque" }
# crossbeam-epoch = { path = "./crossbeam-epoch" }
# crossbeam-skiplist = { path = "./crossbeam-skiplist" }
# crossbeam-utils = { path = "./crossbeam-utils" }
